version: "3"
services:
  nginx-ssl:
    container_name: nginx-ssl
    image: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./content:/usr/share/nginx/html
      - ./vhosts:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
